/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.payroll.system;

import java.awt.HeadlessException;
import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rjay
 */
public final class AssignProject extends javax.swing.JFrame {
    static int lemployee, laproject;
    static String projectName ;
    int xMouse, yMouse;
    /**
     * Creates new form AssignProject
     */
    public AssignProject() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.refreshtblEmp();
        this.refreshtblassignedProject();
        
    }
    public void refreshtblEmp(){
        String[] columns = {"ID","FIRSTNAME","LASTNAME", "DESIGNATION"};
        String whereClause = "emp_status='f' OR designation like '%supervisor%' "
                +" OR designation like '%foreman%' OR designation like '%architect%' or designation like '%engineer%'";
        String[][] records = PG.executeDQL("employee", columns, whereClause);
        UIC.Table.setModel(tblemp, records, columns);
    }
    
    
    public void refreshtblassignedProject(){
        String[] col = {"ID", "NAME"};
        String where = "id="+App.lproject;
        String[][] rec = PG.executeDQL("project", col, where);
        projectName = rec[0][1];
        System.out.println("Project Name: "+projectName);
        lblProjectName.setText(projectName);
        
        String[] columns = {"ID","EMP_FNAME","EMP_LNAME", "DESIGNATION"};
        String whereClause = "projectname='"+projectName+"'";
        String[][] records = PG.executeDQL("employee_project", columns, whereClause);
        UIC.Table.setModel(tblemp_project, records, columns);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        lblProjectName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtSearchAssignEmployee = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblemp_project = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblemp = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_Titlebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Graphics\\icons8_Close_Window_20px.png")); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon("D:\\Graphics\\icons8_Close_Window_20px.png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1450, 790));
        setMinimumSize(new java.awt.Dimension(1450, 790));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1450, 790));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 137, 123));
        jPanel8.setMaximumSize(new java.awt.Dimension(1380, 150));
        jPanel8.setMinimumSize(new java.awt.Dimension(1380, 150));
        jPanel8.setPreferredSize(new java.awt.Dimension(1380, 150));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 60)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Assign Employee(s)");

        jLabel34.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("List of Employees");

        lblProjectName.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        lblProjectName.setForeground(new java.awt.Color(255, 255, 255));
        lblProjectName.setText("Project Name");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(lblProjectName, javax.swing.GroupLayout.PREFERRED_SIZE, 721, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(lblProjectName))
                .addGap(25, 25, 25))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 150));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setMaximumSize(new java.awt.Dimension(1420, 640));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Search_25px.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        txtSearchAssignEmployee.setBackground(new java.awt.Color(245, 245, 245));
        txtSearchAssignEmployee.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtSearchAssignEmployee.setBorder(null);
        txtSearchAssignEmployee.setOpaque(false);
        txtSearchAssignEmployee.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchAssignEmployeeKeyReleased(evt);
            }
        });
        jPanel2.add(txtSearchAssignEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 440, 40));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 440, 10));

        tblemp_project.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblemp_project.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblemp_project.setRowHeight(23);
        tblemp_project.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblemp_projectMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblemp_project);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 500, 510));

        tblemp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblemp.setRowHeight(23);
        tblemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblemp);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 500, 500));

        btnRemove.setBackground(new java.awt.Color(0, 137, 123));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Left_80px_1.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, -1, -1));

        btnAssign.setBackground(new java.awt.Color(0, 137, 123));
        btnAssign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Right_80px.png"))); // NOI18N
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });
        jPanel2.add(btnAssign, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 137, 123));
        jLabel2.setText("Remove");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 120, 40));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 137, 123));
        jLabel4.setText("Assign");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 120, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1450, 600));

        jPanel_Titlebar.setBackground(new java.awt.Color(0, 105, 92));
        jPanel_Titlebar.setMaximumSize(new java.awt.Dimension(1450, 40));
        jPanel_Titlebar.setMinimumSize(new java.awt.Dimension(1450, 40));
        jPanel_Titlebar.setPreferredSize(new java.awt.Dimension(1450, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 191, 165));
        jLabel1.setText("Mesagon Builders | Payroll Management System");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Minimize_Window_25px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Close_Window_25px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Maximize_Window_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_TitlebarLayout = new javax.swing.GroupLayout(jPanel_Titlebar);
        jPanel_Titlebar.setLayout(jPanel_TitlebarLayout);
        jPanel_TitlebarLayout.setHorizontalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitlebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 686, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addGap(48, 48, 48)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TitlebarLayout.setVerticalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitlebarLayout.createSequentialGroup()
                .addGroup(jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel_Titlebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel1MouseDragged

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:

        try{
            String[] col = {"ID", "NAME"};
            String where = "id="+App.lproject;
            String[][] rec = PG.executeDQL("project", col, where);
            String projectn = rec[0][1];

            PG.conn = getConnection(PG.url, PG.username, PG.password);
            PG.stmt = PG.conn.createStatement();
            ResultSet rs = PG.stmt.executeQuery("SELECT * FROM employee WHERE id="+lemployee);

            if(rs.next()){
                String fname = rs.getString("firstname");
                String lname = rs.getString("lastname");
                String des = rs.getString("designation");

                Object[] values = {fname, lname, des, projectn};
                String query = "INSERT INTO employee_project (emp_fname, emp_lname, designation, projectname) VALUES (?,?,?,?)";
                if(PG.executeDML(query, values)){
                    char stat = 't';
                    Object[] val = {stat, projectn, lemployee};
                    //update null - project name
                    String q = "UPDATE employee SET emp_status=?, ongoingproject=? WHERE id=?";

                    if(PG.executeDML(q, val)){
                        System.out.println("F to T");
                    }
                }
                else{
                    javax.swing.JOptionPane.showMessageDialog(null, "An error occured while assigning personnel.");
                }
            }

            PG.conn.close();
        }catch(HeadlessException | SQLException e){
            System.out.println("Connection Error: "+e);
        }
        this.refreshtblEmp();
        this.refreshtblassignedProject();
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int ch = JOptionPane.showConfirmDialog(null, "Continue to remove the personnel in the project?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION);
        if(ch==0){
            try{
                PG.conn = getConnection(PG.url, PG.username, PG.password);
                PG.stmt = PG.conn.createStatement();
                String q = "SELECT * FROM employee_project WHERE id="+laproject;
                ResultSet rs = PG.stmt.executeQuery(q);
                if(rs.next()){
                    //retrieve info from the emp_project table
                    String[] columns = {"emp_fname", "emp_lname", "designation"};
                    String whereClause = "id="+laproject;
                    String[][] records = PG.executeDQL("employee_project", columns, whereClause);

                    String fname = records[0][0];
                    String lname = records[0][1];
                    String des = records[0][2];

                    //to make the personnel available to be assigned in other project
                    Object[] values = {fname, lname, des};
                    String queryUpdate = "UPDATE employee SET emp_status='f', ongoingproject='N/A' WHERE firstname=? AND lastname=? AND designation=?";

                    //remove personnel from the project
                    Object[] key = {laproject};
                    String queryDelete = "DELETE FROM employee_project WHERE id=?";
                    if(PG.executeDML(queryUpdate, values)){
                        boolean executeDML = PG.executeDML(queryDelete, key);
                        if(executeDML){
                            JOptionPane.showMessageDialog(null, "Personnel removed!");
                        }
                    }

                    PG.stmt.executeQuery(queryDelete);
                    //                    if(PG.executeDML(queryDelete)){
                        //                          JOptionPane.showMessageDialog(null, "Personnel Successfully removed in the project!");
                        //                          this.refreshtblEmp();
                        //                           this.refreshtblassignedProject();
                        //                    }
                    JOptionPane.showMessageDialog(null, "Personnel has been removed in the project");

                }

                PG.conn.close();
            }catch(HeadlessException | SQLException e){
                
            }

            this.refreshtblEmp();
            this.refreshtblassignedProject();
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void tblempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempMouseClicked
        // TODO add your handling code here:
        lemployee = UIC.Table.getSelectedRow(tblemp);
    }//GEN-LAST:event_tblempMouseClicked

    private void tblemp_projectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblemp_projectMouseClicked
        // TODO add your handling code here:
        laproject = UIC.Table.getSelectedRow(tblemp_project);
    }//GEN-LAST:event_tblemp_projectMouseClicked

    private void txtSearchAssignEmployeeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchAssignEmployeeKeyReleased
        // TODO add your handling code here:
        String s = txtSearchAssignEmployee.getText();
        
        if(s.equals("")){
            refreshtblEmp();
        }else{
           try{
                PG.conn = getConnection(PG.url, PG.username, PG.password);
                PG.stmt = PG.conn.createStatement();
                 String whereClause = "emp_status='f' OR designation like '%"+s+"%' OR FIRSTNAME LIKE '%"+s+"%' OR LASTNAME like '%"+s+"%' OR MIDDLEINITIAL LIKE '%"+s+"%'";
                String query = "SELECT ID, FIRSTNAME, LASTNAME, DESIGNATION FROM employee WHERE "+whereClause;
                ResultSet rs = PG.stmt.executeQuery(query);
                
                tblemp.setModel(DbUtils.resultSetToTableModel(rs));
                PG.conn.close();
            }catch(SQLException e){
                System.out.println("SQLException error: "+e);
            } 
        }
    }//GEN-LAST:event_txtSearchAssignEmployeeKeyReleased

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Titlebar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JLabel lblProjectName;
    private javax.swing.JTable tblemp;
    private javax.swing.JTable tblemp_project;
    private javax.swing.JTextField txtSearchAssignEmployee;
    // End of variables declaration//GEN-END:variables
}
