/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.payroll.system;


import static java.sql.DriverManager.getConnection;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static project.payroll.system.PG.conn;


/**
 *
 * @author Rjay
 */
public final class Payroll extends javax.swing.JFrame {
    static String pname;
    static int emp, epayroll;
    int xMouse, yMouse;
    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
        UIC.Frame.setDefault(this);
        System.out.println("ID: "+App.lproject);  
        
        String[] columns = {"name"};
        String whereClause = "id="+App.lproject;
        String[][] records = PG.executeDQL("project", columns, whereClause);
        pname = records[0][0];
        lblpname.setText(pname);
        this.showEmployee();
//        String[] column = {"projectname"};
//        String where = "id="+App.lproject;
//        String[][] rec = PG.executeDQL("employee_project", column, where);
//        String projectName = rec[0][0];
//        System.out.println("Project Name: "+projectName);

//        String[] col = {"id", "emp_fname", "emp_lname", "des", "salary"};
        //java.sql.Date dstart = new java.sql.Date(dpayrollS.getDate().getTime());
        //java.sql.Date dend = new java.sql.Date(dpayrollF.getDate().getTime());
//        String where = "datestarted >= '2017-10-06' AND dateended <= '2017-10-12'";
//        String[][] record = PG.executeDQL("payroll", col, where);
//        UIC.Table.setModel(tblpayroll, record, col);
    }
    
    public void showEmployee(){
        String[] columns = {"id","emp_fname", "emp_lname", "designation"};
        String where = "projectname='"+pname+"'";
        String[][] recs = PG.executeDQL("employee_project", columns, where);
        UIC.Table.setModel(tblemp, recs, columns);
    }
    
    public static void showPayroll(){
//        String[] columns = {"id", "emp_fname", "emp_lname", "des", "no_hours", "no_days", "allowance", "deduction_amount", "salary"};
       String[] col = {"id", "emp_fname", "emp_lname", "des", "salary"};
        java.sql.Date dstart = new java.sql.Date(dpayrollS.getDate().getTime());
        java.sql.Date dend = new java.sql.Date(dpayrollF.getDate().getTime());
        String where = "datestarted >= '"+dstart+"' AND dateended <= '"+dend+"' AND projectname='"+pname+"'";
        String[][] record = PG.executeDQL("payroll", col, where);
        UIC.Table.setModel(tblpayroll, record, col);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Titlebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblpname = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txtFname1 = new javax.swing.JTextField();
        jSeparator17 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblpayroll = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblemp = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnPreview = new javax.swing.JButton();
        dpayrollF = new com.toedter.calendar.JDateChooser();
        dpayrollS = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnSalary = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Titlebar.setBackground(new java.awt.Color(0, 105, 92));
        jPanel_Titlebar.setMaximumSize(new java.awt.Dimension(1450, 40));
        jPanel_Titlebar.setMinimumSize(new java.awt.Dimension(1450, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 191, 165));
        jLabel1.setText("Mesagon Builders | Payroll Management System");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Minimize_Window_25px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Close_Window_25px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Maximize_Window_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_TitlebarLayout = new javax.swing.GroupLayout(jPanel_Titlebar);
        jPanel_Titlebar.setLayout(jPanel_TitlebarLayout);
        jPanel_TitlebarLayout.setHorizontalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitlebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 727, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TitlebarLayout.setVerticalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitlebarLayout.createSequentialGroup()
                .addGroup(jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jPanel8.setBackground(new java.awt.Color(0, 137, 123));
        jPanel8.setMaximumSize(new java.awt.Dimension(1380, 150));
        jPanel8.setMinimumSize(new java.awt.Dimension(1380, 150));

        jLabel32.setFont(new java.awt.Font("Segoe UI Light", 1, 60)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Payroll");

        lblpname.setFont(new java.awt.Font("Segoe UI Light", 1, 30)); // NOI18N
        lblpname.setForeground(new java.awt.Color(255, 255, 255));
        lblpname.setText("Project Name");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblpname, javax.swing.GroupLayout.PREFERRED_SIZE, 1068, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblpname)
                .addGap(25, 25, 25))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1450, 150));

        jPanel2.setBackground(new java.awt.Color(245, 245, 245));
        jPanel2.setMaximumSize(new java.awt.Dimension(1420, 640));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Search_25px.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        txtFname1.setBackground(new java.awt.Color(245, 245, 245));
        txtFname1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        txtFname1.setBorder(null);
        txtFname1.setOpaque(false);
        jPanel2.add(txtFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 440, 40));
        jPanel2.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 440, 10));

        tblpayroll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblpayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblpayroll.setRowHeight(23);
        tblpayroll.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpayrollMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblpayroll);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 60, 500, 500));

        tblemp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tblemp.setRowHeight(23);
        tblemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblempMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblemp);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 500, 500));

        btnRemove.setBackground(new java.awt.Color(0, 137, 123));
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Trash_80px.png"))); // NOI18N
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 137, 123));
        jLabel2.setText("Remove");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 120, 40));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 137, 123));
        jLabel6.setText("Preview");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 120, 40));

        btnPreview.setBackground(new java.awt.Color(0, 137, 123));
        btnPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Preview_Pane_80px_1.png"))); // NOI18N
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });
        jPanel2.add(btnPreview, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, -1, -1));

        dpayrollF.setDateFormatString("yyyy/MM/dd");
        dpayrollF.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dpayrollFPropertyChange(evt);
            }
        });
        jPanel2.add(dpayrollF, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, 210, 30));

        dpayrollS.setDateFormatString("yyyy/MM/dd");
        jPanel2.add(dpayrollS, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, 210, 30));

        jLabel7.setText("====");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 30, -1, -1));

        btnSalary.setBackground(new java.awt.Color(0, 137, 123));
        btnSalary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Paycheque_80px_1.png"))); // NOI18N
        btnSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 137, 123));
        jLabel10.setText("Salary");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 120, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1450, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void tblpayrollMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpayrollMouseClicked
        // TODO add your handling code here:
        epayroll = UIC.Table.getSelectedRow(tblpayroll);
    }//GEN-LAST:event_tblpayrollMouseClicked

    private void tblempMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblempMouseClicked
        // TODO add your handling code here:
        emp = UIC.Table.getSelectedRow(tblemp);
        System.out.println("Clicked: "+emp);
    }//GEN-LAST:event_tblempMouseClicked

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int ch = JOptionPane.showConfirmDialog(null, "Continue to remove the personnel in the project?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION);
        if(ch==0){
            try{
                PG.conn = getConnection(PG.url, PG.username, PG.password);
                PG.stmt = PG.conn.createStatement();
                java.sql.Date dstart = new java.sql.Date(dpayrollS.getDate().getTime());
                java.sql.Date dend = new java.sql.Date(dpayrollF.getDate().getTime());
                String query = "DELETE FROM payroll WHERE id="+epayroll;
                PG.stmt.executeUpdate(query);
                
                
                Payroll.showPayroll();
                PG.conn.close();
            }catch(Exception e){
                System.out.println("Connection error");
            }
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        String[] col = {"id", "emp_fname", "emp_lname", "des", "salary"};
        java.sql.Date dstart = new java.sql.Date(dpayrollS.getDate().getTime());
        java.sql.Date dend = new java.sql.Date(dpayrollF.getDate().getTime());
        String where = "datestarted >= '"+dstart+"' AND dateended <= '"+dend+"' AND projectname='"+pname+"'";
        String[][] record = PG.executeDQL("payroll", col, where);
        UIC.Table.setModel(tblpayroll, record, col);
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void dpayrollFPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dpayrollFPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_dpayrollFPropertyChange

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalaryActionPerformed
        // TODO add your handling code here:
        Salary sal = new Salary();
        sal.setVisible(true);
    }//GEN-LAST:event_btnSalaryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSalary;
    public static com.toedter.calendar.JDateChooser dpayrollF;
    public static com.toedter.calendar.JDateChooser dpayrollS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel_Titlebar;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JLabel lblpname;
    private javax.swing.JTable tblemp;
    public static javax.swing.JTable tblpayroll;
    private javax.swing.JTextField txtFname1;
    // End of variables declaration//GEN-END:variables
}
