/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.payroll.system;

import java.awt.Image;
import java.awt.Toolkit;
import static java.sql.DriverManager.getConnection;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author mat
 */
public final class ProjectDetails extends javax.swing.JFrame {
    byte[] imgdata;
    int xMouse;
    int yMouse;
    /**
     * Creates new form EmployeeDetails
     */
    public ProjectDetails() {
        initComponents();
        this.showDetails();
        UIC.Frame.setDefault(this);
        
        PG.url = "jdbc:postgresql://localhost:5432/payrolldb";
        PG.username = "postgres";
        PG.password = "123";
        PG.className = "org.postgresql.Driver";
    }
    
    public void showDetails(){
        
        String[] columns = {"ID", "NAME", "TYPE", "ARCHITECT", "OWNER", "LOCATION", "DATE_STARTED", "DATE_FINISHED"};
        String whereClause = "ID="+App.lproject;
        String records[][] = PG.executeDQL("project",  columns, whereClause);
        
        
        String name = records[0][1];
        String type = records[0][2];
        String arc = records[0][3];
        String owner = records[0][4];
        String loc = records[0][5];
        String dstarted = records[0][6];
        String dfinished = records[0][7];
        
        txtpname.setText(name);
        txttype.setText(type);
        txtarchitect.setText(arc);
        txtowner.setText(owner);
        txtlocation.setText(loc);
        try {
            java.util.Date date2 = new SimpleDateFormat("YYYY-mm-dd").parse(dstarted);
            java.util.Date date3 = new SimpleDateFormat("YYYY-mm-dd").parse(dfinished);
            dcdateStarted.setDate(date2);
            dcdateFinished.setDate(date3);
        } catch (ParseException ex) {
            dcdateFinished.setDate(null);
            dcdateStarted.setDate(null);
        }
    }
    
    public Image stretchImage(String path,JLabel label)
    {
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Image image = toolkit.getImage(path);
        Image scaledImage = image.getScaledInstance(label.getWidth(),label.getHeight(), Image.SCALE_DEFAULT);
        return scaledImage;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Titlebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        jPanel_PersonnelDetails1 = new javax.swing.JPanel();
        jSeparator10 = new javax.swing.JSeparator();
        btn_deleteProject = new javax.swing.JButton();
        jSeparator17 = new javax.swing.JSeparator();
        txtowner = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        txtarchitect = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();
        txttype = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtpname = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        dcdateStarted = new com.toedter.calendar.JDateChooser();
        jLabel52 = new javax.swing.JLabel();
        dcdateFinished = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtlocation = new javax.swing.JTextArea();
        jLabel53 = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1450, 790));
        setMinimumSize(new java.awt.Dimension(1450, 790));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(1450, 790));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Titlebar.setBackground(new java.awt.Color(0, 105, 92));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Close_Window_25px.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 191, 165));
        jLabel1.setText("Mesagon Builders | Payroll Management System");

        javax.swing.GroupLayout jPanel_TitlebarLayout = new javax.swing.GroupLayout(jPanel_Titlebar);
        jPanel_Titlebar.setLayout(jPanel_TitlebarLayout);
        jPanel_TitlebarLayout.setHorizontalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitlebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 901, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TitlebarLayout.setVerticalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitlebarLayout.createSequentialGroup()
                .addGroup(jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1450, 30));

        jPanel10.setBackground(new java.awt.Color(0, 137, 123));
        jPanel10.setMaximumSize(new java.awt.Dimension(1380, 150));
        jPanel10.setMinimumSize(new java.awt.Dimension(1380, 150));
        jPanel10.setPreferredSize(new java.awt.Dimension(1380, 150));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Segoe UI Light", 1, 70)); // NOI18N
        jLabel71.setForeground(new java.awt.Color(255, 255, 255));
        jLabel71.setText("Project Details");
        jPanel10.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 530, 100));
        jPanel10.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1450, 150));

        jPanel_PersonnelDetails1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel_PersonnelDetails1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_PersonnelDetails1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        btn_deleteProject.setBackground(new java.awt.Color(0, 137, 123));
        btn_deleteProject.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btn_deleteProject.setForeground(new java.awt.Color(240, 240, 240));
        btn_deleteProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Delete_25px.png"))); // NOI18N
        btn_deleteProject.setText("Delete");
        btn_deleteProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteProjectActionPerformed(evt);
            }
        });
        jPanel_PersonnelDetails1.add(btn_deleteProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 530, 180, 40));
        jPanel_PersonnelDetails1.add(jSeparator17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 320, 20));

        txtowner.setBackground(new java.awt.Color(245, 245, 245));
        txtowner.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtowner.setBorder(null);
        txtowner.setOpaque(false);
        jPanel_PersonnelDetails1.add(txtowner, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 320, 50));

        jLabel49.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(97, 97, 97));
        jLabel49.setText("Owner:");
        jPanel_PersonnelDetails1.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 120, 30));
        jPanel_PersonnelDetails1.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, 20));

        txtarchitect.setBackground(new java.awt.Color(245, 245, 245));
        txtarchitect.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtarchitect.setBorder(null);
        txtarchitect.setOpaque(false);
        jPanel_PersonnelDetails1.add(txtarchitect, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 320, 50));

        jLabel59.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(97, 97, 97));
        jLabel59.setText("Architect");
        jPanel_PersonnelDetails1.add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, -1, 30));
        jPanel_PersonnelDetails1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 320, 20));

        txttype.setBackground(new java.awt.Color(245, 245, 245));
        txttype.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txttype.setBorder(null);
        txttype.setOpaque(false);
        jPanel_PersonnelDetails1.add(txttype, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 320, 50));

        jLabel50.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(97, 97, 97));
        jLabel50.setText("Type:");
        jPanel_PersonnelDetails1.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 80, 30));
        jPanel_PersonnelDetails1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 320, 20));

        txtpname.setBackground(new java.awt.Color(245, 245, 245));
        txtpname.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtpname.setBorder(null);
        txtpname.setOpaque(false);
        jPanel_PersonnelDetails1.add(txtpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 320, 50));

        jLabel47.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(97, 97, 97));
        jLabel47.setText("Project Name:");
        jPanel_PersonnelDetails1.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 30));

        jLabel57.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(97, 97, 97));
        jLabel57.setText("Date Started:");
        jPanel_PersonnelDetails1.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 160, 30));

        dcdateStarted.setDateFormatString("yyyy/MM/dd");
        dcdateStarted.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jPanel_PersonnelDetails1.add(dcdateStarted, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 280, 50));

        jLabel52.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(97, 97, 97));
        jLabel52.setText("Date of Completion:");
        jPanel_PersonnelDetails1.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 40, 250, 30));

        dcdateFinished.setDateFormatString("yyyy/MM/dd");
        dcdateFinished.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jPanel_PersonnelDetails1.add(dcdateFinished, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 280, 50));

        txtlocation.setBackground(new java.awt.Color(245, 245, 245));
        txtlocation.setColumns(20);
        txtlocation.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        txtlocation.setRows(5);
        txtlocation.setBorder(null);
        jScrollPane2.setViewportView(txtlocation);

        jPanel_PersonnelDetails1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 720, 140));

        jLabel53.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(97, 97, 97));
        jLabel53.setText("Location:");
        jPanel_PersonnelDetails1.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 230, 30));

        btnUpdate.setBackground(new java.awt.Color(0, 137, 123));
        btnUpdate.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(240, 240, 240));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Update_25px.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel_PersonnelDetails1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, 180, 40));

        getContentPane().add(jPanel_PersonnelDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1450, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void btn_deleteProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteProjectActionPerformed
        // TODO add your handling code here:
        
        String[] col = {"ID", "NAME"};
        String where = "id="+App.lproject;
        String[][] rec = PG.executeDQL("project", col, where);
        String pname = rec[0][1];
        System.out.println("PROJECT NAME: "+pname);
        char stat = 'f';
        
        int ch = JOptionPane.showConfirmDialog(null, "Do you want to delete this project?", "Delete Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(ch==0){
            try {
                //update personnel to be available
                String query = "UPDATE employee SET emp_status='f', ongoingProject='N/A' WHERE ongoingProject='"+pname+"'";
                String queryDelete = "DELETE FROM project WHERE id="+App.lproject;
                
                PG.conn = getConnection(PG.url, PG.username, PG.password);
                PG.stmt = PG.conn.createStatement();
                PG.stmt.execute(query);
                PG.stmt.executeUpdate(queryDelete);
                JOptionPane.showMessageDialog(null, "Project has been deleted!");
                txtpname.setText("");
                txttype.setText("");
                txtowner.setText("");
                txtarchitect.setText("");
                txtlocation.setText("");
                dcdateStarted.setDate(null);
                dcdateFinished.setDate(null);
                
                
                String[] columns = {"ID","NAME","TYPE", "ARCHITECT", "OWNER", "LOCATION", "DATE_STARTED", "DATE_FINISHED"};
                String whereClause = "1=1";
                String[][] records = PG.executeDQL("project", columns, whereClause);
                UIC.Table.setModel(App.tblListofProjects, records, columns);
                App.cb_projectname.removeItem(pname);
                this.dispose();
                PG.conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(ProjectDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
    }//GEN-LAST:event_btn_deleteProjectActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int ch = JOptionPane.showConfirmDialog(null,"Do you want to proceed?", "Project Confirmation", JOptionPane.YES_NO_OPTION);
        String pname = txtpname.getText();
        String type = txttype.getText();
        String owner = txtowner.getText();
        String architect = txtarchitect.getText();
        String location = txtlocation.getText();
        //String bday = UIC.DateChooser.getDate(dcdob);

        //convert string to sql date
        java.sql.Date dstarted = new java.sql.Date(dcdateStarted.getDate().getTime());
        java.sql.Date dfinished = new java.sql.Date(dcdateFinished.getDate().getTime());

        Object[] values = {pname, type, architect, owner, location, dstarted, dfinished, App.lproject};
        String query = "UPDATE project SET name=? ,type=?, architect=?, owner=?, location=?, date_started=?, date_finished=? WHERE id=?";

        if(ch==0){
            
            if(PG.executeDML(query, values)){
                javax.swing.JOptionPane.showMessageDialog(null, "Project has been update!");
                //to update automatically the table after disposing the frame
                String[] columns = {"ID","NAME","TYPE", "ARCHITECT", "OWNER", "LOCATION", "DATE_STARTED", "DATE_FINISHED"};
                String whereClause = "1=1";
                String[][] records = PG.executeDQL("project", columns, whereClause);
                UIC.Table.setModel(App.tblListofProjects, records, columns);
                
                txtpname.setText("");
                txttype.setText("");
                txtowner.setText("");
                txtarchitect.setText("");
                txtlocation.setText("");
                dcdateStarted.setDate(null);
                dcdateFinished.setDate(null);
                App.combo_fillProject();
                this.dispose();
            }
            else{
                javax.swing.JOptionPane.showMessageDialog(null, "An error occured while updating Project.");
            }
            
            
            
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjectDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btn_deleteProject;
    private com.toedter.calendar.JDateChooser dcdateFinished;
    private com.toedter.calendar.JDateChooser dcdateStarted;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel_PersonnelDetails1;
    private javax.swing.JPanel jPanel_Titlebar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JTextField txtarchitect;
    private javax.swing.JTextArea txtlocation;
    private javax.swing.JTextField txtowner;
    private javax.swing.JTextField txtpname;
    private javax.swing.JTextField txttype;
    // End of variables declaration//GEN-END:variables
}
