/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.payroll.system;

import static java.sql.DriverManager.getConnection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Rjay
 */
public class Salary extends javax.swing.JFrame {
    String pname;
    int xMouse, yMouse;
    static float rateemp, allow_emp;
    
    /**
     * Creates new form Salary
     */
    public Salary() {
        initComponents();
        String[] columns = {"emp_fname", "emp_lname", "designation"};
        String whereClause = "id="+Payroll.emp;
        String[][] res = PG.executeDQL("employee_project", columns, whereClause);
        txtlname.setText(res[0][1]);
        txtfname.setText(res[0][0]);
        txtdes.setText(res[0][2]);
        
        String fname = res[0][0];
        String lname = res[0][1];
        
        String[] col = {"name"};
        String where = "id="+App.lproject;
        String[][] records = PG.executeDQL("project", col, where);
        pname = records[0][0];
        
        try{
            PG.conn = getConnection(PG.url, PG.username, PG.password);
            PG.stmt = PG.conn.createStatement();
            String where1;
            where1 = "firstname ='"+fname+"' AND lastname='"+lname+"'";
            ResultSet rs = PG.stmt.executeQuery("SELECT * FROM employee Where "+where1);
            
            while(rs.next()){
                rateemp = rs.getFloat("rate");
                String rate1 = String.valueOf(rateemp);
                txtrate.setText(rate1);
                allow_emp = rs.getFloat("allowance");
                String allow1 = String.valueOf(allow_emp);
                txtallowance.setText(allow1);
                
            }
        }catch(SQLException e){
            
        }
        
        UIC.Frame.setDefault(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Titlebar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtlname = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        txtfname = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        txtdes = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        txtrate = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        txthr = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        txtdays = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jSeparator12 = new javax.swing.JSeparator();
        txtallowance = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jSeparator13 = new javax.swing.JSeparator();
        txtded = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtsalary = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btnDone = new javax.swing.JButton();
        jSeparator14 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Titlebar.setBackground(new java.awt.Color(0, 105, 92));
        jPanel_Titlebar.setMaximumSize(new java.awt.Dimension(1450, 40));
        jPanel_Titlebar.setMinimumSize(new java.awt.Dimension(1450, 40));

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(250, 250, 250));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 191, 165));
        jLabel1.setText("Mesagon Builders | Payroll Management System");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Minimize_Window_25px.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Close_Window_25px.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Maximize_Window_25px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel_TitlebarLayout = new javax.swing.GroupLayout(jPanel_Titlebar);
        jPanel_Titlebar.setLayout(jPanel_TitlebarLayout);
        jPanel_TitlebarLayout.setHorizontalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TitlebarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(48, 48, 48)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_TitlebarLayout.setVerticalGroup(
            jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_TitlebarLayout.createSequentialGroup()
                .addGroup(jPanel_TitlebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel_Titlebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 40));

        jPanel1.setBackground(new java.awt.Color(245, 245, 245));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtlname.setEditable(false);
        txtlname.setBackground(new java.awt.Color(245, 245, 245));
        txtlname.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtlname.setBorder(null);
        txtlname.setOpaque(false);
        jPanel1.add(txtlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, 50));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 250, 20));

        jLabel38.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(97, 97, 97));
        jLabel38.setText("Salary:");
        jPanel1.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 100, 50));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 250, 20));

        txtfname.setEditable(false);
        txtfname.setBackground(new java.awt.Color(245, 245, 245));
        txtfname.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtfname.setBorder(null);
        txtfname.setOpaque(false);
        jPanel1.add(txtfname, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 250, 50));

        jLabel39.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(97, 97, 97));
        jLabel39.setText("First Name:");
        jPanel1.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 140, 30));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 60, 250, 20));

        txtdes.setEditable(false);
        txtdes.setBackground(new java.awt.Color(245, 245, 245));
        txtdes.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtdes.setBorder(null);
        txtdes.setOpaque(false);
        jPanel1.add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 250, 50));

        jLabel40.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(97, 97, 97));
        jLabel40.setText("Designation:");
        jPanel1.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 140, 30));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 230, 250, 20));

        txtrate.setBackground(new java.awt.Color(245, 245, 245));
        txtrate.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtrate.setBorder(null);
        txtrate.setOpaque(false);
        jPanel1.add(txtrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 250, 50));

        jLabel41.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(97, 97, 97));
        jLabel41.setText("Rate: */hour");
        jPanel1.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 150, 250, 30));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 250, 20));

        txthr.setBackground(new java.awt.Color(245, 245, 245));
        txthr.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txthr.setBorder(null);
        txthr.setOpaque(false);
        jPanel1.add(txthr, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 250, 50));

        jLabel42.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(97, 97, 97));
        jLabel42.setText("Total Hours Worked:");
        jPanel1.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, 30));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 250, 20));

        txtdays.setBackground(new java.awt.Color(245, 245, 245));
        txtdays.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtdays.setBorder(null);
        txtdays.setOpaque(false);
        jPanel1.add(txtdays, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 250, 50));

        jLabel43.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(97, 97, 97));
        jLabel43.setText("Total Days Worked:");
        jPanel1.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 250, 30));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 250, 20));

        txtallowance.setBackground(new java.awt.Color(245, 245, 245));
        txtallowance.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtallowance.setBorder(null);
        txtallowance.setOpaque(false);
        jPanel1.add(txtallowance, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 250, 50));

        jLabel44.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(97, 97, 97));
        jLabel44.setText("Allowance: */day");
        jPanel1.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 250, 30));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 250, 20));

        txtded.setBackground(new java.awt.Color(245, 245, 245));
        txtded.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtded.setBorder(null);
        txtded.setOpaque(false);
        jPanel1.add(txtded, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 300, 250, 50));

        jLabel45.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(97, 97, 97));
        jLabel45.setText("Deduction: *");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 250, 30));

        jButton2.setBackground(new java.awt.Color(0, 105, 92));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jButton2.setForeground(new java.awt.Color(245, 245, 245));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Money_25px.png"))); // NOI18N
        jButton2.setText("Salary");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 80, -1, 40));

        txtsalary.setEditable(false);
        txtsalary.setBackground(new java.awt.Color(245, 245, 245));
        txtsalary.setFont(new java.awt.Font("SansSerif", 0, 22)); // NOI18N
        txtsalary.setBorder(null);
        txtsalary.setOpaque(false);
        jPanel1.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, 250, 50));

        jLabel46.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(97, 97, 97));
        jLabel46.setText("Last Name:");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 140, 30));

        btnDone.setBackground(new java.awt.Color(0, 105, 92));
        btnDone.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        btnDone.setForeground(new java.awt.Color(245, 245, 245));
        btnDone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/payroll/system/images/icons8_Ok_25px_1.png"))); // NOI18N
        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });
        jPanel1.add(btnDone, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 80, 130, 40));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 230, 250, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1230, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        float ded;
        float hrs = Float.parseFloat(txthr.getText());
        float days = Float.parseFloat(txtdays.getText());
        float rate = Float.parseFloat(txtrate.getText());
        
        if(txtded.getText().equals("")){
            ded = 0;
        }else{
            ded = Float.parseFloat(txtded.getText());
        }
        float allowance = Float.parseFloat(txtallowance.getText());
        
        float tempSalary = (rate*hrs) + (allowance*days);
        float netSalary = tempSalary - ded;
        txtsalary.setText("Php "+netSalary);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        // TODO add your handling code here:
        int ch = JOptionPane.showConfirmDialog(null, "Want to proceed?", "Salary", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if(ch==0){
            //insert
            String fname = txtfname.getText();
            String lname = txtlname.getText();
            String des = txtdes.getText();
            float ded;
            float hrs = Float.parseFloat(txthr.getText());
            float days = Float.parseFloat(txtdays.getText());
            float rate = Float.parseFloat(txtrate.getText());
            if(txtded.getText().equals("")){
                ded = 0;
            }else{
                ded = Float.parseFloat(txtded.getText());
            }
            float allowance = Float.parseFloat(txtallowance.getText());

            float tempSalary = (rate*hrs) + (allowance*days);
            float netSalary = tempSalary - ded;
            java.sql.Date dstart = new java.sql.Date(Payroll.dpayrollS.getDate().getTime());
            java.sql.Date dend = new java.sql.Date(Payroll.dpayrollF.getDate().getTime());
            System.out.println("Start: "+dstart);
            System.out.println("End: "+dend);
            Object[] values = {fname, lname, des, rate, hrs, days, allowance, ded, netSalary, dstart, dend, pname};
            String query = "INSERT INTO payroll (emp_fname, emp_lname, des, rate, no_hours, no_days, allowance, deduction_amount, salary, datestarted, dateended, projectname) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)";
            if(PG.executeDML(query, values)){
                JOptionPane.showMessageDialog(null, "Success!");
                txthr.setText("");
                txtdays.setText("");
                txtrate.setText("");
                txtded.setText("");
                txtallowance.setText("");
                txtsalary.setText("");
                txtfname.setText("");
                txtlname.setText("");
                txtdes.setText("");
                
                String[] col = {"id", "emp_fname", "emp_lname", "des", "salary"};
                java.sql.Date ds = new java.sql.Date(Payroll.dpayrollS.getDate().getTime());
                java.sql.Date de = new java.sql.Date(Payroll.dpayrollF.getDate().getTime());
                String where = "datestarted >= '"+ds+"' AND dateended <= '"+de+"' AND projectname='"+Payroll.pname+"'";
                String[][] record = PG.executeDQL("payroll", col, where);
                UIC.Table.setModel(Payroll.tblpayroll, record, col);
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Error!");
            }
        }
    }//GEN-LAST:event_btnDoneActionPerformed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Salary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Salary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Titlebar;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField txtallowance;
    private javax.swing.JTextField txtdays;
    private javax.swing.JTextField txtded;
    private javax.swing.JTextField txtdes;
    private javax.swing.JTextField txtfname;
    private javax.swing.JTextField txthr;
    private javax.swing.JTextField txtlname;
    private javax.swing.JTextField txtrate;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
